### ISSUE TITLE
Feature Request - Index number for Min and Max

### ISSUE THREAD

**Issue by getSurreal** [MajenkoLibraries/Average#6]
Nice library.  Thanks for sharing.  I don't know if you're taking feature requests, but I thought I'd submit one anyway.

While tracking more than one Average, it would be nice to be able to lookup the corresponding value.

For example when tracking Temperature and Humidity I would be able to look at what the humidity was at the max temperature.

**Comment by getSurreal** [comment]
I was able to make a quick hack to pull the index of min and max

**Comment by majenkotech** [comment]
I have added an optional pointer parameter to the minimum() and maximum() functions so you can pass a pointer to an integer variable and that variable gets filled in with the slice number of the maximum or minimum.  The example has been updated to demonstrate it.  I have also overhauled the internal array access code so that it always goes via the "get" function which works properly with the circular buffer that is used for the internal data store.  Before it didn't really care and just accessed the raw data, but doing that the slice numbers wouldn't always make sense when compared to the results of the get() function.
